                                        #INTRODUCTION TO NUMPY WITH EXAMPLE:-


NumPy (Numerical Python) is a fundamental package for scientific computing with Python and is widely used in various fields such as physics, engineering, signal processing, and data analysis.

**The as np part assigns the alias np to the NumPy library, allowing us to use np instead of numpy to access its functions and classes.

In [4]:
import numpy as np

##The version of NumPy installed on your system using the following method.

In [5]:
np.__version__  ##The version of NumPy installed on your system using the following method.

'2.0.1'

##A NumPy array from a Python list using the np.array() function.**

In [6]:
arr =np.array([25 ,90,79,59,89,78]) ##A NumPy array from a Python list using the np.array() function.
arr

array([25, 90, 79, 59, 89, 78])

##The np.array() function takes a Python list as input and returns a NumPy 
array object.

In [7]:
ls = [25 ,90,79,59,89,78]  ##The np.array() function takes a Python list as input and returns a NumPy array.
arr =np.array(ls)
arr

array([25, 90, 79, 59, 89, 78])

##type(arr),type object contains information about the class, such as its name, base classes, 
 and attributes.

In [8]:
type(arr) ##type(arr),type object contains information about the class, such as its name, base classes. 
 

numpy.ndarray

##the code arr.ndim returns the number of dimensions in the NumPy array arr.

In [9]:
arr.ndim #the code arr.ndim returns the number of dimensions in the NumPy array arr.

1

##the code arr.size returns the total number of elements in the NumPy array arr.

In [10]:
arr.size ##the code arr.size returns the total number of elements in the NumPy array arr.

6

##the code len(arr) returns the number of elements in the first dimension of the NumPy
 array arr.

In [11]:
len(arr) ##the code len(arr) returns the number of elements in the first dimension of the NumPy array.
 

6

##the code arr.dtype returns the data type of the elements in the NumPy array arr.

In [12]:
arr.dtype ##the code arr.dtype returns the data type of the elements in the NumPy array arr.

dtype('int64')

In [13]:
arr =np.array([25 ,90,79,59,89,78,70.5])
arr.dtype

dtype('float64')

In [14]:
arr* 10

array([250., 900., 790., 590., 890., 780., 705.])

In [15]:
arr /5

array([ 5. , 18. , 15.8, 11.8, 17.8, 15.6, 14.1])

##the code arr.dtype returns the data type of the elements in the NumPy array arr.

In [16]:
##the code arr.dtype returns the data type of the elements in the NumPy array arr.
min(arr) 

np.float64(25.0)

##the code max(arr) returns the maximum value in the NumPy array arr.

In [17]:
##the code max(arr) returns the maximum value in the NumPy array arr.
max(arr)

np.float64(90.0)

##the code sum(arr) returns the sum of all elements in the NumPy array arr.

In [18]:
sum(arr) ##the code sum(arr) returns the sum of all elements in the NumPy array arr.

np.float64(490.5)

                                   #STATISTICAL  FUNCTION:-#
                                

1)The code np.mean(arr) returns the arithmetic mean (average) of all elements in the NumPy array arr.

In [19]:
np.mean(arr)

np.float64(70.07142857142857)

2) The code np.median(arr) returns the median (middle value) of all elements in the NumPy array arr.

In [20]:
np.median(arr)

np.float64(78.0)

3) numpy.std() computes the standard deviation of an array.

In [21]:
# Create an array
arr = np.array([1, 2, 3, 4, 5])

# Compute the standard deviation
std = np.std(arr)
print(std)

1.4142135623730951


                                        *Some different  and  unique function:-*

##The code np.random.randint(1, 20) generates a random integer.

In [22]:
np.random.randint(1,20)

15

##string.punctuation is a pre-initialized string constant in Python's string module that contains all the special characters, also known as punctuation characters.

In [23]:
import string
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

##string.digits is a pre-initialized string constant in Python's string module that contains 
all the digit characters.


In [24]:
string.digits

'0123456789'

##Here,string.ascii_letters is a pre-initialized string constant in Python's string module that 
contains all the ASCII letters (both uppercase and lowercase).

In [25]:
string.ascii_letters

'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'

##Here,The np.random.randint function generates an array of random integers within a specified 
range. In this case, the function generates an array arr with the following 
characteristics:
low: 1 (the lowest possible value in the array)
high: 450 (the highest possible value in the array)
size: 500 (the number of elements in the array)

In [26]:
arr =  np.random.randint(1,450,500)
arr

array([362, 368, 396, 358,  11, 333,  51, 191, 422, 381,  62, 256, 448,
       245, 258, 136, 339,  70, 402, 179, 165, 330,  43, 317,  10, 347,
       252, 144,  88, 120, 427, 409, 125, 101, 199,  89, 250, 298, 226,
       355, 230,  38,  25,  59, 137, 105, 119,  19, 225, 421, 169, 276,
        70, 102, 289, 185,  48, 278, 434, 309,  67, 241, 351, 219, 188,
        77, 432, 101, 327, 408, 281, 134, 275, 264, 429, 388, 119, 246,
       277, 436, 194, 237, 130,  85,  53, 357, 394,  74,   2, 201, 168,
       119, 213, 328, 230, 275, 210, 279, 254, 337, 408, 135, 112,  15,
       175, 267, 432, 371,  23, 344,  61, 430, 424,  48, 252, 156, 442,
       366, 203, 356, 416,  14,  14, 351, 399,  85, 132,  24, 284, 407,
       449,  79, 313, 129, 356, 117, 369, 409, 156, 210, 179, 291, 293,
       133,  59,   3,  18, 401, 323, 229, 158, 443, 358,   9, 136, 174,
       155, 183, 227, 261, 380, 334, 193,  50, 147, 388, 161, 228, 261,
       388, 130,  65, 310, 324,  50,  36, 198, 360, 216, 247, 43

##Here,print(f"Number of even numbers: {count}") is a Python statement that uses a feature called
 f-strings (formatted strings) to print no of even value.

In [27]:
count = (arr % 2 == 0).sum()

print(f"Number of even numbers: {count}")

Number of even numbers: 266


##Here,the code is likely using a NumPy array, and we want to find the number of elements in the array
 that are less than 100.

In [28]:
#METHOD 1:-
count = (arr < 100).sum()

print(f"Number of items less than 100: {count}")

Number of items less than 100: 109


In [2]:
#METHOD 2:-
count = len([x for x in arr if x <= 100])
print(count)

NameError: name 'arr' is not defined

In [30]:
#METHOD 3:-
count = 0
for x in arr:
    if x <= 100:
        count += 1
print(count)

111


In [31]:
ls = [[1,2,3],
      [4,5,6],
      [7,8,9]]
ls

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

##type()use to determine the type

In [32]:
type(ls)

list

In [33]:
arr2 =np.array(ls)
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

##.ndim use to determine the dimension.

In [34]:
arr2.ndim 

2

##It is use to determine the shape

In [35]:
arr2.shape 

(3, 3)

In [36]:
arr2[0]  #row

array([1, 2, 3])

In [37]:
arr2[2] #row

array([7, 8, 9])

In [38]:
arr2[0:1]

array([[1, 2, 3]])

In [39]:
arr2[-1]

array([7, 8, 9])

In [40]:
arr2[1:3,1:3]

array([[5, 6],
       [8, 9]])

In [ ]:
arr2[-2:]

##Here,numpy.ones() Creates an array filled with ones.

In [41]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

##Here,numpy.zeros() Creates an array filled with zeros

In [42]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

##np.linspace is a function from the NumPy library in Python that returns evenly spaced numbers over a specified range. It is often used to create arrays with values within a specified interval.

In [43]:
np.linspace(1,20,8)

array([ 1.        ,  3.71428571,  6.42857143,  9.14285714, 11.85714286,
       14.57142857, 17.28571429, 20.        ])

##Here,numpy.reshape() reshapes an array to a new shape.


In [44]:
# Create an array with shape (6,)
arr = np.array([1, 2, 3, 4, 5, 6])

# Reshape the array to (2, 3)
arr = np.reshape(arr, (2, 3))
print(arr)

[[1 2 3]
 [4 5 6]]


##Here,numpy.transpose() transposes an array.

In [45]:
# Create an array with shape (2, 3)
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Transpose the array
arr = np.transpose(arr)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


##Here,numpy.dot() computes the dot product of two arrays.

In [46]:
# Create two arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Compute the dot product
dot_product = np.dot(arr1, arr2)
print(dot_product)

32


                                 *NOW SOME MATHEMATICAL FUNCTION:-*

1) numpy.add():-Element-wise addition of two arrays.

In [47]:
# Create two arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Add the two arrays
arr = np.add(arr1, arr2)
print(arr)

[5 7 9]


2) numpy.subtract():-Element-wise subtraction of two arrays.

In [ ]:
# Create two arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Subtract the two arrays
arr = np.subtract(arr1, arr2)
print(arr) 

3) numpy.multiply():-Element-wise multiplication of two arrays.

In [48]:
# Create two arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Multiply the two arrays
arr = np.multiply(arr1, arr2)
print(arr) 

[ 4 10 18]


4) numpy.divide():-Element-wise division of two arrays

In [49]:
# Create two arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Divide the two arrays
arr = np.divide(arr1, arr2)
print(arr)

[0.25 0.4  0.5 ]


                                 **Some Basic Function:-**

1)numpy.where() is a function that allows you to perform conditional operations on arrays.

In [50]:
import numpy as np

# Create an array
arr = np.array([1, 2, 3, 4, 5])

# Use where() to replace values greater than 3 with 0
new_arr = np.where(arr > 3, 0, arr)

print(new_arr)  

[1 2 3 0 0]


2)numpy.unique():- returns the unique elements of an array.


In [51]:
import numpy as np

# Create an array
arr = np.array([1, 2, 2, 3, 4, 4, 5])

# Get unique elements
unique_arr = np.unique(arr)

print(unique_arr)  # Output: [1, 2, 3, 4, 5]

[1 2 3 4 5]


3)numpy.diff() calculates the differences between consecutive elements of an array.

In [52]:
import numpy as np
# Create an array
arr = np.array([1, 2, 4, 7, 11])

# Calculate the differences between consecutive elements
diff_arr = np.diff(arr)

print(diff_arr)  # Output: [1, 2, 3, 4]

[1 2 3 4]


4)numpy.arange(): Create a NumPy array with a specified range of values.

In [53]:
import numpy as np
arr = np.arange(0, 10, 2)
print(arr)  # Output: [0, 2, 4, 6, 8]

[0 2 4 6 8]


5)numpy.meshgrid(): Create a 2D grid of NumPy arrays.

In [54]:
import numpy as np
x = np.linspace(0, 10, 5)
y = np.linspace(0, 10, 5)
X, Y = np.meshgrid(x, y)
print(X)
print(Y)  

[[ 0.   2.5  5.   7.5 10. ]
 [ 0.   2.5  5.   7.5 10. ]
 [ 0.   2.5  5.   7.5 10. ]
 [ 0.   2.5  5.   7.5 10. ]
 [ 0.   2.5  5.   7.5 10. ]]
[[ 0.   0.   0.   0.   0. ]
 [ 2.5  2.5  2.5  2.5  2.5]
 [ 5.   5.   5.   5.   5. ]
 [ 7.5  7.5  7.5  7.5  7.5]
 [10.  10.  10.  10.  10. ]]


6)numpy.flip(): Flip a NumPy array.

In [55]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
arr = np.flip(arr)
print(arr)  # Output: [5, 4, 3, 2, 1]

[5 4 3 2 1]


7)numpy.rot90(): Rotate a NumPy array by 90 degrees.

In [56]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr = np.rot90(arr)
print(arr)  # Output: [[3, 6], [2, 5], [1, 4]]

[[3 6]
 [2 5]
 [1 4]]
